version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:10
    branches: 
      only:
        - master
    steps:
      - add_ssh_keys:  
          fingerprints:  
            - "a5:37:7d:8d:37:5d:9f:a4:80:61:ef:16:6c:36:f4:2a"
      - checkout
      - run: 
        name: Install
        command: npm install
      - run:  
        name: Build 
        command: npm run build
