version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:16
    branches: 
      only:
        - main
    steps:
      - add_ssh_keys:  
          fingerprints:  
            - "ac:c6:cd:0e:5d:db:9d:b5:91:8a:bd:1f:39"
      - checkout
      - restore_cache:
          keys:  
            - node_dependencies  
      - run: 
          name: Install
          command: npm install
      - save_cache:  
          paths:  
            - node_modules
          key: node_dependencies  
      - run:  
          name: Build 
          command: npm run build
      - run:
          name: Prepare shell commands 
          # 在根目录下新建scripts目录，在此目录新建deploy.sh
          # shell chmod +x 赋予执行权限
          # 执行shell脚本 
          command: chmod +x scripts/deploy.sh
      - run:
          name: Run Deploy to Github pages 
          command: ./scripts/deploy.sh
